services:
    elasticoxid.connector:
        class: ElasticOxid\Connector\Connector
    elasticoxid.oxid.object.oxcontent:
        class: ElasticOxid\Type\Content
        arguments: [@elasticoxid.connector]
    elasticoxid.oxid.object.oxarticle:
        class: ElasticOxid\Type\Article